version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: meme_gallery
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: ./api
    container_name: meme_gallery_api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: meme_gallery
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
